### ISSUE TITLE
Feature Request, no_std support

### ISSUE THREAD

**Issue by orclev** [althonos/textwrap-macros#12]
Nothing in the generated output of the proc macros requires std so adding `#![no_std]` to `src/lib.rs` would allow the macros to be used in no_std crates. I've tested this out with my own fork and confirmed it works, but I don't want to screw up the changelog and release style you've got going. Should be a one line change.

**Comment by althonos** [comment]
Hi @orclev, I made a new release with `no_std` as a feature (the usual, the crate compiles by default with the `std` feature enabled, compiling the crate without default features will cause it to be `no_std`).
